# Generated by Django 3.2.4 on 2021-10-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongComments',
        ),
    ]
