# Generated by Django 3.2.4 on 2021-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_songcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomments',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Your comment'),
        ),
    ]
