# Generated by Django 3.2.4 on 2021-09-07 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time')),
                ('liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Liked by')),
                ('song_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='private.song', verbose_name='Song like')),
            ],
        ),
    ]
