# Generated by Django 3.2.4 on 2021-09-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0004_auto_20210915_1013'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlikes',
            name='song_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.song', verbose_name='Song like'),
        ),
    ]
