# Generated by Django 3.2.4 on 2021-07-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=100, verbose_name='Author of the post')),
                ('band', models.CharField(max_length=100, verbose_name='Band')),
                ('name', models.CharField(max_length=50, verbose_name='Song')),
                ('album', models.CharField(max_length=50, verbose_name='Album')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='Post date')),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.genre')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
    ]
