# Generated by Django 3.2.3 on 2021-06-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
