# Generated by Django 3.2.4 on 2021-09-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Listening counter'),
        ),
    ]
