# Generated by Django 3.2.3 on 2021-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_remove_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='band',
            field=models.CharField(max_length=50, verbose_name='Band'),
        ),
    ]
