# Generated by Django 3.2.4 on 2021-09-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_song_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
    ]
