# Generated by Django 3.2.4 on 2021-09-15 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private', '0003_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Playlist author'),
        ),
        migrations.CreateModel(
            name='SongPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.playlist', verbose_name='Song playlist')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.song', verbose_name='Song playlist')),
            ],
            options={
                'db_table': 'songplaylist',
            },
        ),
    ]
