# Generated by Django 3.2.4 on 2021-10-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0004_auto_20210915_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songplaylist',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.playlist', verbose_name='Playlist'),
        ),
        migrations.AlterField(
            model_name='songplaylist',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.song', verbose_name='Song'),
        ),
    ]
