# Generated by Django 3.2.3 on 2021-06-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0004_auto_20210623_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': ('Post date',)},
        ),
        migrations.AlterModelTable(
            name='album',
            table=('albums',),
        ),
    ]
